# Generated by Django 4.2.7 on 2023-11-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('horario_monitoria', models.TextField()),
                ('dia_da_semana', models.TextField()),
                ('sala', models.TextField()),
                ('nome_monitor', models.TextField()),
            ],
        ),
    ]
