# Generated by Django 4.2.7 on 2023-11-22 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_reply_profile_post_comment_post_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='contador',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='contador',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tempo_ativo',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
