# Generated by Django 4.2.7 on 2023-11-25 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_profile_tempo_ativo_profile_filme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='filme',
            new_name='movie',
        ),
        migrations.AddField(
            model_name='profile',
            name='tempo_ativo',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
