# Generated by Django 4.2.7 on 2023-11-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_filme_profile_movie_profile_tempo_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movie',
            field=models.ManyToManyField(to='forum.movie'),
        ),
    ]
